# heros API
api:
  heroCamp: https://pvp.qq.com/act/a20160510story/herostory.htm
  heroList: https://pvp.qq.com/webplat/info/news_version3/15592/18024/23901/24397/24398/m17330/list_1.shtml

# File storage root path
sourcePath: source/

# Heros Database
database:
  heroInfo:
    # Origin
    herosOrigin: info/origin
    detailOrigin: info/origin/heros-detail
    # New
    herosNew: info/new
    detailNew: info/new/heros-detail
  heroPic:
    heroimg: img/hero/
    heroface: img/face/
